# Generated by Django 5.2.5 on 2025-08-25 01:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "hourly_rate_min",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "hourly_rate_max",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("part-time", "Part-time"),
                            ("full-time", "Full-time"),
                            ("seasonal", "Seasonal"),
                            ("gig", "Gig"),
                            ("internship", "Internship"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("part-time", "Part-time"),
                            ("full-time", "Full-time"),
                            ("flexible", "Flexible"),
                            ("weekends", "Weekends"),
                            ("evenings", "Evenings"),
                            ("summer", "Summer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=4.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField()),
                ("availability", models.JSONField(default=list)),
                ("why_interested", models.TextField()),
                ("relevant_experience", models.TextField()),
                ("questions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Application Submitted"),
                            ("under_review", "Under Review"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interviewed", "Interviewed"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_date"],
                "unique_together": {("job", "applicant")},
            },
        ),
    ]
