# Generated by Django 5.2.5 on 2025-08-24 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name_plural': 'Dashboard'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': 'Resumes'},
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='xp_awarded',
            new_name='task_xp',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='applied_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='financegoal',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='financegoal',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
