# Generated by Django 5.2.5 on 2025-08-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_dashboard_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='location',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='status',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='company',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='financegoal',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
