# Generated by Django 5.2.5 on 2025-08-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_dashboard_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='created_at',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('offer', 'Offer')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='company',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
