# Generated by Django 5.2.5 on 2025-08-24 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_achievement_created_at_appliedjob_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-awarded_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='appliedjob',
            options={'ordering': ['-applied_on', 'company']},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['start', 'school_name']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start', 'company']},
        ),
        migrations.AlterModelOptions(
            name='financegoal',
            options={'ordering': ['due_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='awarded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='achievement',
            name='awarded_on',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='applied_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='financegoal',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financegoal',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
